language: bash
before_install:
- sudo apt-get install texlive texlive-xetex texlive-math-extra texlive-latex-recommended texlive-full
- wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-linux.tar.gz
- tar xvfz pandoc-2.6-linux.tar.gz
script:
- bash deploy.sh
deploy:
- provider: pages
- skip_cleanup: true
- github_token: https://csakou:$GITHUB_TOKEN@github.com/csakou/resume.git  # Set in the settings page of your repository, as a secure variable
- keep_history: true
- on:
    branch: master
