language: bash
before_install:
- sudo apt-get install texlive texlive-full
- wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-linux.tar.gz
- tar xvfz pandoc-2.6-linux.tar.gz
script:
- bash deploy.sh
after_success:
- bash push.sh
