braches:
  only:
  - master
language: bash
env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH
before_install:
- wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
  && ar p pandoc-2.1.1-1-amd64.deb data.tar.xz | tar xJ
- sudo apt-get update -qq
- sudo apt-get install texlive texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra  texlive-science texlive-full
- sudo apt-get install lmodern
- chmod +x push.sh
script:
- make pdf
- set +u
after_success:
- "./push.sh"
