# Site
repository: p16sako/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Sakoumpentas Christos
title: Informatics Student
email: c.sakoumpentas@protonmail.com
phone: +30 694 144 3074
website: csakou.github.io/pw

# Social links
twitter_username:
github_username: 'csakou'
dribbble_username:
facebook_username: 'Febarios.Celcios'
flickr_username:
instagram_username:
linkedin_username: 'christos sakoumpentas'
xing_username:
pinterest_username:
youtube_username:
googleplus_username:

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://github.com/csakou/pw/blob/master/img/20190218_105918.jpg?raw=true
about_content: | # this will include new lines to allow paragraphs
 I am studying informatics at the [Ionian University](http://di.ionio.gr). 
 I am aspiring to learn as much as possible about what Computations are, the Processing of Information, 
 and to become an expert Programmer. All in all i strive so that at the time this experience is over, 
 i will know deeply about about computing, information and every part that makes a computer what it is.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - **Interests**
  
  *Computer Networks*, *Computer Programming*, *Machine Learning*, *Network Security*, 
  *Cyber Security*, *Internet Security*, *Computer Security*, *Automata Theory*, *Algorithms and Complexibility*.
  
  - **Skills**
  
  *Teamwork*, *Desire to learn*, *Adapting easilly*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
