---
# Site
repository: csakou/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Sakoumpentas Christos
title: Informatics Student
address:
- Georgiou Karidi 
- 49100 Corfu
- Greece

email: c.sakoumpentas@protonmail.com
gmail: sakoumpentas@gmail.com
phone: "+30 694 144 3074"
homepage: csakou.github.io/pw
resume: csakou.github.io/resume

# Social links
twitter_username:
github_username: csakou
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: christos-sakoumpentas-2b9b96172
xing_username:
pinterest_username:
youtube_username:
googleplus_username:

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://github.com/csakou/pw/blob/master/img/20190218_105918.jpg?raw=true
intro: | # this will include new lines to allow paragraphs
 I am studying informatics at the [Ionian University](http://di.ionio.gr).
 My interests so far lie in the 

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)
experience:
- employer: 'Swissport'
  link: 
  job: Airport Check-In Agent
  years: 'July2019 - October 2019'
  city: 'Corfu'
  quite: >
  description: |
  As a check-in agent my responsibilites included passport check and identification, accepting payments for certain
  flight services, greeting the passengers and informing them of the procedures required to board their flight.

- employer: 'Oblix'
  link: https://www.oblixrestaurant.com
  job: Commis Waiter       
  years: 'July 2017 - October 2017'
  city: 'London'           
  quote: >
  description: | # this will include new lines to allow paragraphs
   As a commis waiter i had the responsibility of serving food to the tables, cleaning and setting them up,
   taking care of the tables and making sure everyone had a pleasant time. Other responsibilities included taking orders,
   serving drinks and assisting as needed on the floor. 

# Education Section
# educaton_title: Education #(Use this to override about education section title)
education:
- institute: Ionian University
  year: "2016 -- Currently"
  qualification: Bachelor of Science
  subject: Informatics
  city: Corfu
  quote: >
  description: |
    I am studying Informatics to aquire a B.S. degree and learn all the core concepts about how Databases, Operating Systems,
    Computer Networks and Computer Programming works. We are also being taught about the importance of Teamwork, working with 
    tight Deadlines and Managing Projects.

    The course also tought me about how computer graphics work, what is and how to use information retrieval techniques,
    machine learning and pattern recognition and lastly about virtual worlds and entertainment software.

languages:
    - language: Greek
      proficiency: Native Fluency
      quote: >
      description: |
      
    - language: English
      proficiency: Edexcel Lower Certificate
      quote: >
      description: |
     
    - language: French
      proficiency: Basic Communication
      quote: >
      description: |

skills:
- Desire to Learn, Adapting Easilly, Team Working
- Hard working, Managing Projects

interests:
- Automata Theory, Machine Learning, Artificial Intelligence
- Discrete Mathematics, Programming, Software Engineering

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

# Settings
mainfont: FreeSerif
fontsize: 10pt
lang: en
geometry: a4paper, left=35mm, right=35mm, top=51mm, bottom=17mm

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
---
