jobs:
  build:
    machine:
      pre:
        - sudo apt-get install texlive-xetex
    working_directory: ~/resume
    steps:
      - checkout
      - run:
          name: Install Texlive
          command: 'sudo apt update && sudo apt install texlive texlive-xetex texlive-fonts-extra texlive-latex-extra texlive-plain-extra'
      - run:
          name: Install Pandoc
          command: 'sudo apt update && sudo apt install pandoc'
          
      - store_artifacts:
          path: /tmp/artifacts
